# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a33327c7698f5bba1bcd664a323110ff852a937d88311dc0d2d0f17727aa0752923b738f2644ec05dc850643c31b50ea6885ee22911e9d7beb41cee410c9076d

test:
  secret_key_base: 4bd6ec9ec20ad727f99d72105ce092bafe7b735e70cdb8d0b47ebee683d1e0ff70ef325539985ff82d5cddf68fa01b1b5e55ea8826eaf924752efc870211a90e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
